import { StyleSheet } from 'react-native'
import { palette } from '../../theme/palette'

export const profileScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: palette.background,
  },
  errorText: {
    textAlign: 'center',
    color: palette.danger,
    fontSize: 16,
  },
  infoText: {
    textAlign: 'center',
    color: palette.textSecondary,
    fontSize: 16,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    padding: 24,
    backgroundColor: palette.background,
  },
  avatarWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginTop: 16,
    marginBottom: 24,
    overflow: 'hidden',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.overlay,
  },
  avatarInitial: {
    fontSize: 48,
    fontWeight: '600',
    color: palette.accent,
  },
  card: {
    width: '100%',
    backgroundColor: palette.surface,
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 1,
    borderColor: palette.border,
  },
  cardLabel: {
    fontSize: 14,
    color: palette.textMuted,
    marginTop: 12,
  },
  cardValue: {
    fontSize: 18,
    color: palette.textPrimary,
    fontWeight: '500',
    marginTop: 4,
  },
  balanceRow: {
    marginTop: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: palette.overlay,
    borderWidth: 1,
    borderColor: palette.border,
  },
  balanceValue: {
    fontSize: 20,
    color: palette.accent,
    fontWeight: '700',
  },
  balanceHint: {
    marginTop: 4,
    color: palette.textSecondary,
    fontSize: 13,
  },
  section: {
    width: '100%',
    marginTop: 32,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: palette.textPrimary,
    marginBottom: 16,
  },
  emptyState: {
    fontSize: 16,
    color: palette.textMuted,
  },
  listingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: palette.surface,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: palette.border,
  },
  listingImageWrapper: {
    width: 72,
    height: 72,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: palette.overlay,
    marginRight: 12,
  },
  listingImage: {
    width: '100%',
    height: '100%',
  },
  listingImagePlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listingImagePlaceholderText: {
    fontSize: 12,
    color: palette.textMuted,
    textAlign: 'center',
  },
  listingInfo: {
    flex: 1,
  },
  listingInfoHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  listingTitle: {
    flex: 1,
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '600',
    color: palette.textPrimary,
    marginRight: 12,
  },
  listingPrice: {
    fontSize: 15,
    color: palette.accent,
    marginTop: 6,
    fontWeight: '500',
  },
  listingDate: {
    fontSize: 13,
    color: palette.textMuted,
    marginTop: 4,
  },
  favoriteButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  favoriteButtonDisabled: {
    opacity: 0.6,
  },
  favoriteIcon: {
    fontSize: 18,
    color: palette.textPrimary,
  },
  favoriteIconActive: {
    color: palette.danger,
  },
  signOutButton: {
    marginTop: 32,
    backgroundColor: palette.danger,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
  },
  signOutButtonText: {
    color: palette.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
})
