import { StyleSheet } from 'react-native'
import { palette } from '../../theme/palette'

export const profileScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: palette.background,
  },
  errorText: {
    textAlign: 'center',
    color: palette.danger,
    fontSize: 16,
  },
  infoText: {
    textAlign: 'center',
    color: palette.textSecondary,
    fontSize: 16,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 8,
    paddingVertical: 16,
    backgroundColor: palette.background,
  },
  avatarWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginTop: 16,
    marginBottom: 24,
    overflow: 'hidden',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.overlay,
  },
  avatarInitial: {
    fontSize: 48,
    fontWeight: '600',
    color: palette.accent,
  },
  card: {
    width: '100%',
    backgroundColor: palette.surface,
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 1,
    borderColor: palette.border,
  },
  cardLabel: {
    fontSize: 14,
    color: palette.textMuted,
    marginTop: 12,
  },
  cardValue: {
    fontSize: 18,
    color: palette.textPrimary,
    fontWeight: '500',
    marginTop: 4,
  },
  section: {
    width: '100%',
    marginTop: 32,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: palette.textPrimary,
    marginBottom: 16,
  },
  emptyState: {
    fontSize: 16,
    color: palette.textMuted,
  },
  listingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: palette.surface,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: palette.border,
  },
  listingImageWrapper: {
    width: 72,
    height: 72,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: palette.overlay,
    marginRight: 12,
  },
  listingImage: {
    width: '100%',
    height: '100%',
  },
  listingImagePlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listingImagePlaceholderText: {
    fontSize: 12,
    color: palette.textMuted,
    textAlign: 'center',
  },
  listingInfo: {
    flex: 1,
  },
  listingInfoHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  listingTitle: {
    flex: 1,
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '600',
    color: palette.textPrimary,
    marginRight: 12,
  },
  listingPrice: {
    fontSize: 15,
    color: palette.accent,
    marginTop: 6,
    fontWeight: '500',
  },
  listingDate: {
    fontSize: 13,
    color: palette.textMuted,
    marginTop: 4,
  },
  favoriteButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  favoriteButtonDisabled: {
    opacity: 0.6,
  },
  favoriteIcon: {
    fontSize: 18,
    color: palette.textPrimary,
  },
  favoriteIconActive: {
    color: palette.danger,
  },
  signOutButton: {
    marginTop: 32,
    backgroundColor: palette.danger,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
  },
  signOutButtonText: {
    color: palette.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  
  // Nouveaux styles pour les fonctionnalités améliorées
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: palette.textSecondary,
  },
  container: {
    flex: 1,
    backgroundColor: palette.background,
  },
  header: {
    paddingHorizontal: 8,
    paddingTop: 24,
    paddingBottom: 16,
    backgroundColor: palette.background,
    alignItems: 'center',
  },
  input: {
    width: '100%',
    maxWidth: '90%',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: palette.textPrimary,
    marginBottom: 16,
  },
  name: {
    fontSize: 28,
    fontWeight: 'bold',
    color: palette.textPrimary,
    marginBottom: 8,
    textAlign: 'center',
  },
  email: {
    fontSize: 16,
    color: palette.textSecondary,
    marginLeft: 8,
  },
  joiningDate: {
    fontSize: 14,
    color: palette.textMuted,
    marginLeft: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  separator: {
    height: 1,
    backgroundColor: palette.border,
    width: '100%',
    marginVertical: 20,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    paddingVertical: 16,
  },
  statColumn: {
    alignItems: 'center',
    flex: 1,
  },
  iconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: palette.accent,
    marginLeft: 8,
  },
  statLabel: {
    fontSize: 14,
    color: palette.textSecondary,
  },
  button: {
    backgroundColor: palette.accent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
    marginTop: 16,
    minWidth: 200,
  },
  buttonText: {
    color: palette.background,
    fontSize: 16,
    fontWeight: 'bold',
  },
  saveButton: {
    backgroundColor: palette.success,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
    marginTop: 16,
    minWidth: 200,
  },
  saveButtonText: {
    color: palette.background,
    fontSize: 16,
    fontWeight: 'bold',
  },
  cancelButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: palette.danger,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
    marginTop: 12,
    minWidth: 200,
  },
  cancelButtonText: {
    color: palette.danger,
    fontSize: 16,
    fontWeight: 'bold',
  },
  activitySection: {
    paddingHorizontal: 8,
    paddingVertical: 16,
    alignItems: 'center',
  },
  activityTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: palette.textPrimary,
    marginBottom: 4,
  },
  activitySubtitle: {
    fontSize: 14,
    color: palette.textMuted,
    textAlign: 'center',
  },
  sectionDivider: {
    height: 1,
    backgroundColor: palette.border,
    width: '100%',
    marginTop: 16,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: palette.surface,
    marginHorizontal: 8,
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: 'transparent',
  },
  activeTab: {
    backgroundColor: palette.accent,
  },
  tabContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabText: {
    fontSize: 14,
    color: palette.textSecondary,
    fontWeight: '500',
  },
  tabTabTextActive: {
    color: palette.background,
    fontWeight: 'bold',
  },
  tabNumber: {
    fontSize: 14,
    color: palette.textMuted,
    fontWeight: '500',
  },
  tabNumberActive: {
    color: palette.background,
    fontWeight: 'bold',
  },
  listWrapper: {
    flex: 1,
    paddingHorizontal: 8,
  },
  listContainer: {
    paddingBottom: 24,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 48,
  },
  emptyStateText: {
    fontSize: 16,
    color: palette.textMuted,
    textAlign: 'center',
  },
})
