import { StyleSheet } from 'react-native'
import { palette } from '../../theme/palette'

const FONT_FAMILY = 'OTJubileeGolden'

export const profileScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.darkGrey,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: palette.darkGrey,
  },
  errorText: {
    textAlign: 'center',
    color: palette.danger,
    fontSize: 16,
    fontFamily: FONT_FAMILY,
  },
  infoText: {
    textAlign: 'center',
    color: palette.textSecondary,
    fontSize: 16,
    fontFamily: FONT_FAMILY,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 0,
    paddingVertical: 0,
    backgroundColor: palette.darkGrey,
  },
  avatarWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginTop: 16,
    marginBottom: 24,
    overflow: 'hidden',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.overlay,
  },
  avatarInitial: {
    fontSize: 48,
    fontWeight: '600',
    color: palette.mustard,
    fontFamily: FONT_FAMILY,
  },
  card: {
    width: '100%',
    backgroundColor: palette.surface,
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 1,
    borderColor: palette.border,
  },
  cardLabel: {
    fontSize: 14,
    color: palette.textMuted,
    marginTop: 12,
    fontFamily: FONT_FAMILY,
  },
  cardValue: {
    fontSize: 18,
    color: palette.textPrimary,
    fontWeight: '500',
    marginTop: 4,
    fontFamily: FONT_FAMILY,
  },
  balanceRow: {
    marginTop: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: palette.overlay,
    borderWidth: 1,
    borderColor: palette.border,
  },
  balanceValue: {
    fontSize: 20,
    color: palette.darkMustard,
    fontWeight: '700',
    fontFamily: FONT_FAMILY,
  },
  balanceHint: {
    marginTop: 4,
    color: palette.textSecondary,
    fontSize: 13,
    fontFamily: FONT_FAMILY,
  },
  section: {
    width: '100%',
    marginTop: 24,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: palette.mustard,
    marginBottom: 20,
    fontFamily: FONT_FAMILY,
  },
  emptyState: {
    fontSize: 16,
    color: palette.textMuted,
    fontFamily: FONT_FAMILY,
  },
  listingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: palette.surface,
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  listingImageWrapper: {
    width: 100,
    height: 100,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: palette.overlay,
    marginRight: 16,
  },
  listingImage: {
    width: '100%',
    height: '100%',
  },
  listingImagePlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listingImagePlaceholderText: {
    fontSize: 12,
    color: palette.textMuted,
    textAlign: 'center',
    fontFamily: FONT_FAMILY,
  },
  listingInfo: {
    flex: 1,
  },
  listingInfoHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  listingTitle: {
    flex: 1,
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '600',
    color: palette.textPrimary,
    marginRight: 12,
    fontFamily: FONT_FAMILY,
  },
  listingPrice: {
    fontSize: 15,
    color: palette.mustard,
    marginTop: 6,
    fontWeight: '500',
    fontFamily: FONT_FAMILY,
  },
  listingDate: {
    fontSize: 13,
    color: palette.textMuted,
    marginTop: 4,
    fontFamily: FONT_FAMILY,
  },
  listingCardInactive: {
    borderColor: palette.danger,
    backgroundColor: palette.elevated,
  },
  listingTitleInactive: {
    color: palette.textSecondary,
  },
  listingPriceInactive: {
    color: palette.textSecondary,
  },
  listingDateInactive: {
    color: palette.textMuted,
  },
  inactiveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  inactiveBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 107, 107, 0.12)',
    borderWidth: 1,
    borderColor: palette.danger,
  },
  inactiveBadgeText: {
    color: palette.danger,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.4,
    fontFamily: FONT_FAMILY,
  },
  activateButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: palette.mustard,
    minWidth: 110,
    alignItems: 'center',
  },
  activateButtonText: {
    color: palette.background,
    fontSize: 14,
    fontWeight: '700',
    fontFamily: FONT_FAMILY,
  },
  activateButtonDisabled: {
    opacity: 0.6,
  },
  favoriteButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  favoriteButtonDisabled: {
    opacity: 0.6,
  },
  favoriteIcon: {
    fontSize: 18,
    color: palette.textPrimary,
    fontFamily: FONT_FAMILY,
  },
  favoriteIconActive: {
    color: palette.darkMustard,
  },
  signOutButton: {
    marginTop: 40,
    marginBottom: 100,
    marginHorizontal: 20,
    backgroundColor: palette.danger,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 12,
    width: 'auto',
    alignItems: 'center',
  },
  signOutButtonText: {
    color: palette.textPrimary,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: FONT_FAMILY,
  },
  
  // Nouveaux styles pour les fonctionnalités améliorées
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: palette.textSecondary,
    fontFamily: FONT_FAMILY,
  },
  container: {
    flex: 1,
    backgroundColor: palette.darkGrey,
  },
  header: {
    paddingHorizontal: 8,
    paddingTop: 0,
    paddingBottom: 0,
    backgroundColor: 'transparent',
    alignItems: 'center',
  },
  input: {
    width: '100%',
    maxWidth: '90%',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: palette.textPrimary,
    marginBottom: 16,
    fontFamily: FONT_FAMILY,
  },
  name: {
    fontSize: 32,
    fontWeight: 'bold',
    color: palette.champagne,
    marginBottom: 8,
    textAlign: 'center',
    fontFamily: FONT_FAMILY,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  ratingStar: {
    marginRight: 2,
    position: 'relative',
  },
  ratingStarFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    overflow: 'hidden',
  },
  ratingValue: {
    marginLeft: 6,
    fontSize: 25,
    fontWeight: 'bold',
    color: palette.darkMustard,
    fontFamily: FONT_FAMILY,
  },
  email: {
    fontSize: 16,
    color: palette.textSecondary,
    marginLeft: 8,
    fontFamily: FONT_FAMILY,
  },
  joiningDate: {
    fontSize: 14,
    color: palette.textMuted,
    marginLeft: 8,
    fontFamily: FONT_FAMILY,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  separator: {
    height: 1,
    backgroundColor: palette.border,
    width: '100%',
    marginVertical: 20,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    paddingVertical: 16,
  },
  statColumn: {
    alignItems: 'center',
    flex: 1,
  },
  iconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: palette.mustard,
    marginLeft: 8,
    fontFamily: FONT_FAMILY,
  },
  statLabel: {
    fontSize: 14,
    color: palette.textSecondary,
    fontFamily: FONT_FAMILY,
  },
  button: {
    backgroundColor: palette.mustard,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
    marginTop: 16,
    minWidth: 200,
  },
  buttonText: {
    color: palette.background,
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: FONT_FAMILY,
  },
  saveButton: {
    backgroundColor: palette.success,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
    marginTop: 16,
    minWidth: 200,
  },
  saveButtonText: {
    color: palette.background,
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: FONT_FAMILY,
  },
  cancelButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: palette.danger,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
    marginTop: 12,
    minWidth: 200,
  },
  cancelButtonText: {
    color: palette.danger,
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: FONT_FAMILY,
  },
  activitySection: {
    paddingHorizontal: 8,
    paddingVertical: 16,
    alignItems: 'center',
  },
  activityTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: palette.champagne,
    marginBottom: 4,
    fontFamily: FONT_FAMILY,
  },
  activitySubtitle: {
    fontSize: 14,
    color: palette.textMuted,
    textAlign: 'center',
    fontFamily: FONT_FAMILY,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: palette.border,
    width: '100%',
    marginTop: 16,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: palette.surface,
    marginHorizontal: 8,
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: 'transparent',
  },
  activeTab: {
    backgroundColor: palette.mustard,
  },
  tabContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabText: {
    fontSize: 14,
    color: palette.textSecondary,
    fontWeight: '500',
    fontFamily: FONT_FAMILY,
  },
  tabTabTextActive: {
    color: palette.background,
    fontWeight: 'bold',
  },
  tabNumber: {
    fontSize: 14,
    color: palette.textMuted,
    fontWeight: '500',
    fontFamily: FONT_FAMILY,
  },
  tabNumberActive: {
    color: palette.background,
    fontWeight: 'bold',
  },
  listWrapper: {
    flex: 1,
    paddingHorizontal: 8,
  },
  listContainer: {
    paddingBottom: 24,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 48,
  },
  emptyStateText: {
    fontSize: 16,
    color: palette.textMuted,
    textAlign: 'center',
    fontFamily: FONT_FAMILY,
  },
  
  // New mockup design styles
  gradientHeader: {
    width: '100%',
    paddingTop: 60,
    paddingBottom: 0,
    paddingHorizontal: 0,
  },
  welcomeContainer: {
    marginBottom: 40,
    paddingHorizontal: 24,
  },
  welcomeText: {
    fontSize: 48,
    fontFamily: 'OTJubileeGolden-Extralight',
    fontWeight: '200',
    color: palette.white,
    letterSpacing: 1,
  },
  welcomeName: {
    fontSize: 52,
    fontFamily: 'OTJubileeGolden-ExtraboldItalic',
    fontStyle: 'italic',
    fontWeight: '700',
    color: palette.white,
    letterSpacing: 1,
  },
  topTabBar: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingBottom: 0,
    gap: 0,
  },
  topTab: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: palette.champagne,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    backgroundColor: palette.darkGrey,
    minHeight: 40,
    overflow: 'hidden',
  },
  topTabGradientBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  topTabMiddle: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  topTabActiveNoBottomBorder: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomColor: 'transparent',
  },
  topTabLeftAdjacentToActive: {
    borderBottomRightRadius: 0,
  },
  topTabRightAdjacentToActive: {
    borderBottomLeftRadius: 0,
  },
  topTabContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 26,
  },
  topTabIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topTabIconActive: {
    backgroundColor: 'transparent',
  },
  topTabIconImage: {
    width: 20,
    height: 20,
    tintColor: palette.champagne,
  },
  topTabLabel: {
    fontSize: 17,
    color: palette.champagne,
    fontWeight: '400',
    fontFamily: FONT_FAMILY,
  },
  topTabLabelActive: {
    color: palette.champagne,
    fontWeight: '600',
    fontFamily: FONT_FAMILY,
  },
  contentWrapper: {
    flex: 1,
    backgroundColor: palette.darkGrey,
  },
  profilePhotoSection: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  personalDataHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 8,
  },
  personalDataTitle: {
    fontSize: 28,
    fontWeight: '600',
    color: palette.mustard,
    fontFamily: FONT_FAMILY,
  },
  editIconButton: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editIcon: {
    width: 16,
    height: 16,
    tintColor: palette.mustard,
  },
  closeIcon: {
    width: 16,
    height: 16,
    tintColor: palette.mustard,
  },
  starIcon: {
    width: 32,
    height: 32,
    tintColor: palette.mustard,
  },
  personalDataInput: {
    width: '100%',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: palette.textPrimary,
    marginBottom: 16,
    fontFamily: FONT_FAMILY,
  },
  verificationCard: {
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 16,
  },
  verificationTitle: {
    fontSize: 28,
    fontWeight: '600',
    color: palette.mustard,
    marginBottom: 16,
    fontFamily: FONT_FAMILY,
  },
  verificationContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  verificationAvatar: {
    width: 86,
    height: 86,
    borderRadius: 43,
    marginRight: 16,
    position: 'relative',
    overflow: 'visible',
  },
  verificationAvatarImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: palette.mustard,
  },
  verificationBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 28,
    height: 28,
    borderRadius: 14,
    overflow: 'hidden',
  },
  verificationBadgeGradient: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
  },
  verificationBadgeText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: palette.lightGrey,
    fontFamily: FONT_FAMILY,
  },
  verificationInfo: {
    flex: 1,
  },
  verificationQuote: {
    fontSize: 14,
    color: palette.textSecondary,
    fontStyle: 'italic',
    lineHeight: 20,
    marginBottom: 8,
    fontFamily: FONT_FAMILY,
  },
  verificationRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    marginRight: 16,
  },
  verificationRatingValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: palette.white,
    marginRight: 8,
    fontFamily: FONT_FAMILY,
  },
  reviewButton: {
    backgroundColor: palette.mustard,
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 8,
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewButtonText: {
    fontSize: 20,
    fontWeight: '600',
    color: palette.champagne,
    fontFamily: FONT_FAMILY,
  },
  verificationDetails: {
    marginTop: 20,
    paddingTop: 16,
    paddingLeft: 8,
  },
  verificationDetailsText: {
    fontSize: 14,
    color: palette.textMuted,
    lineHeight: 22,
    fontFamily: 'BaiJamjuree-Regular',
  },
  reviewsButtonContainer: {
    paddingHorizontal: 20,
    marginTop: 16,
    marginBottom: 8,
  },
  viewReviewsButton: {
    backgroundColor: palette.mustard,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewReviewsButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: palette.background,
    fontFamily: FONT_FAMILY,
  },
  personalDataSection: {
    paddingHorizontal: 20,
  },
  personalDataLabel: {
    fontSize: 12,
    color: palette.lightGrey,
    fontStyle: 'italic',
    marginTop: 20,
    marginBottom: 2,
    fontWeight: '400',
    fontFamily: 'OTJubileeGolden-ExtralightItalic',
  },
  personalDataValue: {
    fontSize: 18,
    color: palette.white,
    fontWeight: '500',
    fontFamily: FONT_FAMILY,
  },
  smartAlertsCard: {
    backgroundColor: palette.mustard,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smartAlertsText: {
    flex: 1,
  },
  smartAlertsTitle: {
    fontSize: 27,
    fontWeight: 'bold',
    color: palette.champagne,
    marginBottom: 2,
    fontFamily: FONT_FAMILY,
  },
  smartAlertsDescription: {
    fontSize: 15,
    color: palette.lightGrey,
    marginTop: 10,
    marginLeft: 12,
    marginRight: 12,
    opacity: 0.8,
    fontFamily: 'BaiJamjuree-Regular',
  },
  recentlyViewedSection: {
    paddingHorizontal: 20,
    marginTop: 32,
    marginBottom: 24,
  },
  recentlyViewedTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: palette.mustard,
    marginBottom: 20,
    fontFamily: FONT_FAMILY,
  },
  recentlyViewedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  recentlyViewedCard: {
    width: '48%',
    backgroundColor: palette.surface,
    borderRadius: 16,
    marginBottom: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  recentlyViewedImage: {
    width: '100%',
    height: 140,
    backgroundColor: palette.overlay,
  },
  recentlyViewedInfo: {
    padding: 12,
  },
  recentlyViewedName: {
    fontSize: 14,
    fontWeight: '600',
    color: palette.white,
    marginBottom: 6,
    fontFamily: FONT_FAMILY,
  },
  recentlyViewedPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: palette.mustard,
    fontFamily: FONT_FAMILY,
  },
  recentlyViewedHeart: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  
  // Favorite cars grid styles
  favoriteSection: {
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  favoriteSectionTitle: {
    fontSize: 28,
    fontWeight: '600',
    color: palette.mustard,
    marginBottom: 24,
    fontFamily: FONT_FAMILY,
  },
  favoriteGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  favoriteCard: {
    width: '48%',
    backgroundColor: palette.surface,
    borderRadius: 16,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  favoriteImageWrapper: {
    width: '100%',
    height: 160,
    backgroundColor: palette.overlay,
    position: 'relative',
  },
  favoriteImage: {
    width: '100%',
    height: '100%',
  },
  favoriteImagePlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.elevated,
  },
  favoriteImagePlaceholderText: {
    fontSize: 13,
    color: palette.textMuted,
    textAlign: 'center',
    fontFamily: FONT_FAMILY,
  },
  favoriteInfo: {
    padding: 12,
    backgroundColor: palette.lightGrey,
  },
  favoriteTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: palette.darkGrey,
    marginBottom: 8,
    minHeight: 42,
    fontFamily: FONT_FAMILY,
    lineHeight: 21,
  },
  favoritePriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  favoriteHeartButton: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    marginLeft: -8,
  },
  favoritePrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: palette.darkGrey,
    fontFamily: FONT_FAMILY,
  },
  
  // Published cars grid styles
  publishedSection: {
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  publishedSectionTitle: {
    fontSize: 28,
    fontWeight: '600',
    color: palette.mustard,
    marginBottom: 24,
    fontFamily: FONT_FAMILY,
  },
  publishedSectionTitleInactive: {
    fontSize: 28,
    fontWeight: '600',
    color: palette.mustard,
    marginBottom: 24,
    fontFamily: FONT_FAMILY,
  },
  publishedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  publishedCard: {
    width: '48%',
    backgroundColor: palette.surface,
    borderRadius: 16,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  publishedCardInactive: {
    width: '48%',
    backgroundColor: palette.surface,
    borderRadius: 16,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: palette.darkMustard,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
    opacity: 0.85,
  },
  publishedImageWrapper: {
    width: '100%',
    height: 160,
    backgroundColor: palette.overlay,
    position: 'relative',
  },
  publishedImage: {
    width: '100%',
    height: '100%',
  },
  publishedImagePlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.elevated,
  },
  publishedImagePlaceholderText: {
    fontSize: 13,
    color: palette.textMuted,
    textAlign: 'center',
    fontFamily: FONT_FAMILY,
  },
  inactiveOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: palette.darkMustard,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  inactiveOverlayText: {
    fontSize: 11,
    fontWeight: '700',
    color: palette.white,
    fontFamily: FONT_FAMILY,
  },
  publishedInfo: {
    padding: 12,
    backgroundColor: palette.lightGrey,
  },
  publishedInfoInactive: {
    padding: 12,
    backgroundColor: 'rgba(187, 126, 29, 0.15)',
  },
  publishedTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: palette.darkGrey,
    marginBottom: 8,
    minHeight: 42,
    fontFamily: FONT_FAMILY,
    lineHeight: 21,
  },
  publishedTitleInactive: {
    fontSize: 16,
    fontWeight: '600',
    color: palette.darkMustard,
    marginBottom: 8,
    minHeight: 42,
    fontFamily: FONT_FAMILY,
    lineHeight: 21,
  },
  publishedBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  publishedBottomRowInactive: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  publishedPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: palette.darkGrey,
    fontFamily: FONT_FAMILY,
  },
  publishedPriceInactive: {
    fontSize: 16,
    fontWeight: 'bold',
    color: palette.darkMustard,
    fontFamily: FONT_FAMILY,
  },
  reactivateButton: {
    backgroundColor: palette.mustard,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    minWidth: 70,
    alignItems: 'center',
  },
  reactivateButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#000000',
    fontFamily: FONT_FAMILY,
  },
})
