import { StyleSheet } from 'react-native'
import { palette } from '../../theme/palette'

export const purchaseScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.darkGrey,
  },
  // Header
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingVertical: 16,
    backgroundColor: palette.darkGrey,
    borderBottomWidth: 0,
  },
  headerTitle: {
    color: palette.mustard,
    fontSize: 16,
    fontFamily: 'OTJubileeGolden',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  iconButton: {
    padding: 8,
  },
  scrollContent: {
    padding: 20,
    backgroundColor: palette.darkGrey,
    paddingBottom: 80,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: palette.white,
    fontFamily: 'OTJubileeGolden-Extrabold',
  },
  subtitle: {
    marginTop: 6,
    marginBottom: 14,
    color: palette.champagne,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'BaiJamjuree-Regular',
  },
  card: {
    backgroundColor: palette.darkGrey,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: palette.darkMustard,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  cardTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: palette.white,
    marginRight: 12,
    fontFamily: 'OTJubileeGolden',
  },
  cardPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.mustard,
    fontFamily: 'OTJubileeGolden-Extrabold',
  },
  cardSubtitle: {
    marginTop: 8,
    color: palette.champagne,
    fontSize: 14,
    fontFamily: 'BaiJamjuree-Regular',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.white,
    marginBottom: 12,
    fontFamily: 'OTJubileeGolden',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  rowSpacing: {
    marginTop: 12,
  },
  rowItem: {
    flex: 1,
  },
  label: {
    color: palette.champagne,
    fontSize: 14,
    fontFamily: 'BaiJamjuree-Regular',
  },
  value: {
    color: palette.white,
    fontWeight: '600',
    fontSize: 15,
    fontFamily: 'OTJubileeGolden',
  },
  divider: {
    height: 1,
    backgroundColor: palette.darkMustard,
    marginVertical: 10,
  },
  formGroup: {
    marginTop: 10,
  },
  inputLabel: {
    color: palette.champagne,
    fontSize: 13,
    marginBottom: 6,
    fontFamily: 'BaiJamjuree-Regular',
  },
  input: {
    backgroundColor: palette.darkGrey,
    borderRadius: 10,
    padding: 12,
    color: palette.white,
    borderWidth: 1,
    borderColor: palette.darkMustard,
    fontSize: 15,
    fontFamily: 'BaiJamjuree-Regular',
  },
  inputPlaceholder: {
    color: palette.champagne,
  },
  primaryButton: {
    backgroundColor: palette.mustard,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 6,
  },
  primaryButtonPressed: {
    backgroundColor: palette.champagne,
  },
  primaryButtonText: {
    color: palette.darkGrey,
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'OTJubileeGolden',
  },
  primaryButtonTextPressed: {
    color: palette.darkMustard,
  },
  disabledHint: {
    marginTop: 8,
    color: palette.champagne,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'BaiJamjuree-Regular',
  },
  secondaryButton: {
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: palette.darkMustard,
    backgroundColor: palette.darkGrey,
  },
  secondaryButtonText: {
    color: palette.white,
    fontSize: 15,
    fontWeight: '600',
    fontFamily: 'OTJubileeGolden',
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  errorBox: {
    backgroundColor: 'rgba(255, 107, 107, 0.12)',
    borderWidth: 1,
    borderColor: palette.danger,
    padding: 12,
    borderRadius: 10,
    marginBottom: 10,
  },
  errorText: {
    color: palette.danger,
    fontSize: 14,
    fontFamily: 'BaiJamjuree-Regular',
  },
  infoBox: {
    marginTop: 8,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.darkMustard,
    backgroundColor: palette.darkGrey,
  },
  infoTitle: {
    color: palette.white,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
    fontFamily: 'OTJubileeGolden',
  },
  infoText: {
    color: palette.champagne,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'BaiJamjuree-Regular',
  },
  successBox: {
    backgroundColor: 'rgba(141, 228, 123, 0.12)',
    borderWidth: 1,
    borderColor: palette.success,
    padding: 12,
    borderRadius: 10,
    marginBottom: 10,
  },
  successText: {
    color: palette.success,
    fontSize: 14,
    fontFamily: 'BaiJamjuree-Regular',
  },
  loader: {
    marginTop: 30,
    alignItems: 'center',
  },
  confirmationHeader: {
    alignItems: 'center',
    marginBottom: 16,
  },
  successIconContainer: {
    marginBottom: 16,
  },
  confirmationIcon: {
    fontSize: 48,
    color: palette.success,
    marginBottom: 6,
  },
  confirmationTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: palette.white,
    fontFamily: 'OTJubileeGolden-Extrabold',
  },
  confirmationSubtitle: {
    marginTop: 6,
    color: palette.champagne,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    fontFamily: 'BaiJamjuree-Regular',
  },
  emptyBox: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: palette.darkGrey,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.darkMustard,
  },
  emptyText: {
    color: palette.champagne,
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 12,
    fontFamily: 'BaiJamjuree-Regular',
  },
  // Payment Selection Styles
  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.darkMustard,
    marginBottom: 12,
    backgroundColor: palette.darkGrey,
  },
  paymentOptionSelected: {
    borderColor: palette.mustard,
    backgroundColor: 'rgba(187, 126, 29, 0.15)',
  },
  paymentOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: palette.champagne,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  radioButtonSelected: {
    borderColor: palette.mustard,
  },
  radioButtonInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.mustard,
  },
  cardDetails: {
    justifyContent: 'center',
  },
  cardBrand: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'OTJubileeGolden',
  },
  cardExpiry: {
    color: palette.champagne,
    fontSize: 12,
    marginTop: 2,
    fontFamily: 'BaiJamjuree-Regular',
  },
  addCardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.darkMustard,
    borderStyle: 'dashed',
    marginTop: 8,
  },
  addCardText: {
    color: palette.white,
    fontSize: 15,
    fontWeight: '500',
    fontFamily: 'OTJubileeGolden',
  },
  // Confirmation Screen Styles (Mockup Design)
  confirmationSafeArea: {
    flex: 1,
    backgroundColor: '#000000',
  },
  confirmationBackButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 10,
    padding: 8,
  },
  confirmationHeaderTitle: {
    alignItems: 'center',
    paddingTop: 20,
    paddingBottom: 10,
  },
  confirmationBrandTitle: {
    fontSize: 18,
    fontFamily: 'OTJubileeGolden-Italic',
    color: palette.white,
    letterSpacing: 2,
    fontStyle: 'italic',
  },
  confirmationScrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 60,
    alignItems: 'center',
  },
  confirmationSuccessIcon: {
    marginTop: 20,
    marginBottom: 30,
  },
  confirmationCircleOuter: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: palette.mustard,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmationCircleInner: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: palette.mustard,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-45deg' }],
  },
  confirmationMainTitle: {
    fontSize: 27,
    fontFamily: 'OTJubileeGolden',
    color: palette.white,
    textAlign: 'center',
    marginBottom: 10,
  },
  confirmationMainSubtitle: {
    fontSize: 16,
    fontFamily: 'BaiJamjuree-Regular',
    color: palette.white,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 30,
  },
  confirmationVehicleCard: {
    width: '100%',
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: palette.mustard,
    borderRadius: 12,
    padding: 24,
    marginBottom: 30,
  },
  confirmationVehicleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  confirmationVehicleColumnLeft: {
    flex: 1.5,
    paddingRight: 20,
  },
  confirmationVehicleColumnRight: {
    flex: 1,
    alignItems: 'flex-end',
  },
  confirmationVehicleLabel: {
    fontSize: 18,
    fontFamily: 'OTJubileeGolden-ExtralightItalic',
    color: palette.white,
    fontStyle: 'italic',
    marginBottom: 6,
  },
  confirmationVehicleValue: {
    fontSize: 27,
    fontFamily: 'OTJubileeGolden',
    color: palette.white,
    fontWeight: '600',
  },
  confirmationPaymentDetails: {
    width: '100%',
    marginBottom: 25,
  },
  confirmationPaymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  confirmationPaymentLabel: {
    fontSize: 12,
    fontFamily: 'BaiJamjuree-Regular',
    color: palette.champagne,
  },
  confirmationPaymentValue: {
    fontSize: 12,
    fontFamily: 'BaiJamjuree-Regular',
    color: palette.white,
  },
  confirmationPaymentDivider: {
    height: 1,
    backgroundColor: palette.darkMustard,
    marginVertical: 8,
  },
  confirmationRateButton: {
    width: '100%',
    backgroundColor: palette.mustard,
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 10,
  },
  confirmationRateButtonPressed: {
    backgroundColor: palette.champagne,
  },
  confirmationRateButtonText: {
    fontSize: 16,
    fontFamily: 'BaiJamjuree-Regular',
    color: palette.darkGrey,
    fontWeight: '500',
  },
  confirmationRateButtonTextPressed: {
    color: palette.darkMustard,
  },
  confirmationInfoText: {
    fontSize: 14,
    fontFamily: 'BaiJamjuree-Regular',
    color: palette.white,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 20,
  },
})
